(** File generated by coq-of-ocaml *)

Require Import ZArith. (* added manually *)
Require Import ExtrOcamlNatInt.
Require Import ExtrOcamlZBigInt.

(* for bug 3 *)
(* From CoqOfOCaml Require Import CoqOfOCaml.
From CoqOfOCaml Require Import Settings. *)

Inductive bar : Set :=
| A : bar
| B : nat -> bar. (* Line 1 *)

Inductive bar2 : Set :=
| X : bar2
| Y : bar2 -> bar2.

Definition foo (l_value : bar) : bool :=
  match l_value with
  | A => true
  | B 2 => false  (* Line 2 *)
  | _ => true
  end.


From QuickChick Require Import QuickChick.
QCInclude "./prop.ml".
Derive (Show, Arbitrary) for bar.
Extract Inductive bar => "Prop.bar"
  [
    "Prop.A"
    "Prop.B"
  ].
Extract Constant foo => "Prop.foo".
QuickChick foo.
