(** File generated by nikhil *)
Require Import ExtrOcamlNatInt.
From QuickChick Require Import QuickChick.
QCDune "dune".

Inductive tree : Set :=
| E : tree
| T : tree -> nat -> nat -> tree -> tree.
Axiom prop_InsertPost : tree -> nat -> nat -> nat -> bool .
Derive (Show, Arbitrary) for tree.
Extract Inductive tree => "Impl.tree"
  [
    "Impl.E"
    "Impl.T"
  ].
Extract Constant prop_InsertPost => "Impl.prop_InsertPost".
QCInclude "/Users/nikhil/Code/Research/quickchick_ocaml/impl.ml".
QuickChick prop_InsertPost.
