lib: [
  "_build/install/default/lib/quickchick_ocaml/META"
  "_build/install/default/lib/quickchick_ocaml/convert.ml"
  "_build/install/default/lib/quickchick_ocaml/dune-package"
  "_build/install/default/lib/quickchick_ocaml/files.ml"
  "_build/install/default/lib/quickchick_ocaml/opam"
  "_build/install/default/lib/quickchick_ocaml/quickchick_ocaml.a"
  "_build/install/default/lib/quickchick_ocaml/quickchick_ocaml.cma"
  "_build/install/default/lib/quickchick_ocaml/quickchick_ocaml.cmi"
  "_build/install/default/lib/quickchick_ocaml/quickchick_ocaml.cmt"
  "_build/install/default/lib/quickchick_ocaml/quickchick_ocaml.cmx"
  "_build/install/default/lib/quickchick_ocaml/quickchick_ocaml.cmxa"
  "_build/install/default/lib/quickchick_ocaml/quickchick_ocaml.ml"
  "_build/install/default/lib/quickchick_ocaml/quickchick_ocaml__.cmi"
  "_build/install/default/lib/quickchick_ocaml/quickchick_ocaml__.cmt"
  "_build/install/default/lib/quickchick_ocaml/quickchick_ocaml__.cmx"
  "_build/install/default/lib/quickchick_ocaml/quickchick_ocaml__.ml"
  "_build/install/default/lib/quickchick_ocaml/quickchick_ocaml__Convert.cmi"
  "_build/install/default/lib/quickchick_ocaml/quickchick_ocaml__Convert.cmt"
  "_build/install/default/lib/quickchick_ocaml/quickchick_ocaml__Convert.cmx"
  "_build/install/default/lib/quickchick_ocaml/quickchick_ocaml__Files.cmi"
  "_build/install/default/lib/quickchick_ocaml/quickchick_ocaml__Files.cmt"
  "_build/install/default/lib/quickchick_ocaml/quickchick_ocaml__Files.cmx"
]
libexec: [
  "_build/install/default/lib/quickchick_ocaml/quickchick_ocaml.cmxs"
]
bin: [
  "_build/install/default/bin/quickchick_ocaml"
]
